set -g status-style "fg=#E9F7F8"
set -g status-right "#[fg=#CDBEDF,bold] %d %B %y - %H:%M "
set -g window-status-format "#{?#{==:#{session_windows},1},, #[fg=#D8ECED,nobold]#I.#W }"
set -g window-status-current-format "#{?#{==:#{session_windows},1},, #[fg=#CDBEDF,bold]*.#W }"
set -g pane-border-style "fg=#010017"
set -g pane-active-border-style "fg=#817889"
