set-option -sa terminal-overrides ",xterm*:Tc"
set -g base-index 1
set-option -g renumber-windows on

# Keybindings

# Prefix: Ctrl+s
set -g prefix C-s

# Reload config
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# Pane navigation (vim-style)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Window navigation with Alt+number
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9
bind -n M-0 select-window -t 10

# Status bar
set -g mouse on
setw -g mode-keys vi
set -g status-position bottom
set -g status-interval 5
set -g status on
if-shell "[ -f ~/.config/tmux/theme.conf ]" \
  "source-file ~/.config/tmux/theme.conf"
bind-key -n C-_ if-shell '[ "$(tmux display-message -p "#I")" = "1" ]' \
  'if-shell "tmux select-window -t 2" "" "new-window"' \
  'select-window -t 1'
# Window list left, clock centred
set -g status-left ""
set -g status-justify left

set -g window-status-style          "default"
set -g window-status-current-style  "default"
set -g window-status-separator      ""

set -g status-format[0] "#[align=left]#{W:#{E:window-status-format},#{E:window-status-current-format}}#{?#{==:#{session_windows},1},#[align=centre],#[align=right]}#{E:status-right}"

# Tmux sessionizer (prefix+f)
bind-key -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer"

# Toggle status bar with prefix+y
bind y if-shell '[ "$(tmux show-option -gv status)" != "off" ]' \
    'set -g status off' \
    'set -g status on'

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Initialize TPM (keep at bottom)
run '~/.tmux/plugins/tpm/tpm'
