### Window appearance (Minimal)
#
default_border none
default_floating_border none

gaps inner 0
gaps outer 0

# SwayFX effects (Disabled for Minimal)
corner_radius 0

# blur off
blur disable
blur_xray off
blur_passes 0
blur_radius 0
default_dim_inactive 0.15

for_window [app_id=".*"] opacity $opacity
for_window [class=".*"] opacity $opacity
for_window [app_id="kitty"] opacity 1
