### Window appearance (Minimal)
#
default_border pixel 1
default_floating_border pixel 1

gaps inner 0
gaps outer 0

# SwayFX effects (Disabled for Minimal)
corner_radius 0

# blur off
blur enable
blur_xray off
blur_passes 1
blur_radius 3
default_dim_inactive 0.1

for_window [app_id=".*"] opacity $opacity
for_window [class=".*"] opacity $opacity
for_window [app_id="kitty"] opacity 1
