-- Hardware detection runs first; every module below branches on its result.
require("conf.hardware")
require("conf.env")
require("conf.monitors")
require("conf.input")
require("conf.general")
require("conf.appearance")
require("conf.opacity")
require("conf.autostart")
require("conf.keybindings")
require("conf.rules")
