[manager]
cwd             = { fg = "#80a0ff" }
hovered         = { fg = "#080808", bg = "#80a0ff" }
preview_hovered = { underline = true }

find_keyword  = { fg = "#e3c78a", bold = true, italic = true, underline = true }
find_position = { fg = "#cf87e8", bg = "reset", bold = true, italic = true }

marker_copied   = { fg = "#8cc85f", bg = "#8cc85f" }
marker_cut      = { fg = "#ff5454", bg = "#ff5454" }
marker_marked   = { fg = "#cf87e8", bg = "#cf87e8" }
marker_selected = { fg = "#80a0ff", bg = "#80a0ff" }

tab_active   = { fg = "#080808", bg = "#80a0ff" }
tab_inactive = { fg = "#bdbdbd", bg = "#2c2c2c" }
tab_width    = 1

count_copied   = { fg = "#080808", bg = "#8cc85f" }
count_cut      = { fg = "#080808", bg = "#ff5454" }
count_selected = { fg = "#080808", bg = "#80a0ff" }

border_symbol = "│"
border_style  = { fg = "#636379" }

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#2c2c2c", bg = "#2c2c2c" }

mode_normal = { fg = "#080808", bg = "#80a0ff", bold = true }
mode_select = { fg = "#080808", bg = "#8cc85f", bold = true }
mode_unset  = { fg = "#080808", bg = "#ff5454",    bold = true }

progress_label  = { bold = true }
progress_normal = { fg = "#80a0ff", bg = "#2c2c2c" }
progress_error  = { fg = "#ff5454",    bg = "#2c2c2c" }

perm_type  = { fg = "#80a0ff" }
perm_read  = { fg = "#e3c78a" }
perm_write = { fg = "#ff5454" }
perm_exec  = { fg = "#8cc85f" }
perm_sep   = { fg = "#636379" }

[input]
border   = { fg = "#80a0ff" }
title    = {}
value    = {}
selected = { reversed = true }

[completion]
border   = { fg = "#80a0ff" }
active   = { bg = "#2c2c2c" }
inactive = {}

[tasks]
border  = { fg = "#80a0ff" }
title   = {}
hovered = { underline = true }

[which]
mask            = { bg = "#1c1c1c" }
cand            = { fg = "#79dac8" }
rest            = { fg = "#9e9d9d" }
desc            = { fg = "#cf87e8" }
separator       = "  "
separator_style = { fg = "#636379" }

[help]
on      = { fg = "#cf87e8" }
run     = { fg = "#cf87e8" }
desc    = { fg = "#9e9d9d" }
hovered = { bg = "#2c2c2c", bold = true }
footer  = { fg = "#2c2c2c", bg = "#bdbdbd" }

[filetype]
rules = [
  { mime = "image/*",                     fg = "#79dac8" },
  { mime = "video/*",                     fg = "#cf87e8" },
  { mime = "audio/*",                     fg = "#e3c78a" },
  { mime = "application/zip",             fg = "#ff5454" },
  { mime = "application/gzip",            fg = "#ff5454" },
  { mime = "application/x-tar",           fg = "#ff5454" },
  { mime = "application/x-bzip2",         fg = "#ff5454" },
  { mime = "application/x-7z-compressed", fg = "#ff5454" },
  { mime = "application/x-rar",           fg = "#ff5454" },
  { name = "*",                           fg = "#bdbdbd" },
  { name = "*/",                          fg = "#80a0ff" },
]
