### Window appearance
#
default_border none
default_floating_border none

gaps inner 4
gaps outer 2

# SwayFX effects
corner_radius 15
shadows on
shadow_blur_radius 20
shadow_color #0000007f

blur on
blur_xray off
blur_passes 2
blur_radius 8
default_dim_inactive 0.15

# layer_effects "waybar" {
# 	blur enable;
# 	blur_xray enable;
# 	blur_ignore_transparent enable;
# }

# layer_effects "swaync-control-center" {
# 	blur enable;
# 	blur_ignore_transparent enable;
# 	shadows enable;
# }

# layer_effects "swaync-notification-window" {
# 	blur enable;
# 	blur_ignore_transparent enable;
# 	shadows enable;
# }


for_window [app_id=".*"] opacity $opacity
for_window [class=".*"] opacity $opacity
for_window [app_id="kitty"] opacity 1
