### Input configuration
#

input type:keyboard {
    xkb_layout us,ara
    xkb_options caps:escape_shifted_capslock,ctrl:swap_lalt_lctl,grp:alt_shift_toggle
}

input type:touchpad {
    tap enabled
    natural_scroll enabled
    dwt enabled
    middle_emulation enabled
}
