set $background #150E0E
set $foreground #F8E4DC
set $color0     #0E0A0A
set $color1     #A4A08D
set $color2     #A09197
set $color3     #6B6EC6
set $color4     #DA5757
set $color5     #9098A1
set $color6     #BB8A76
set $color7     #F1D8CF
set $color8     #775E5E
set $color9     #A5A38C
set $color10    #A38E96
set $color11    #6E71F0
set $color12    #FF3332
set $color13    #97A4B4
set $color14    #F5AF94
set $color15    #F1D8CF

# target                 border   bg       text     indicator child_border
client.focused           $color4  $color4  $background  $color12  $color4
client.focused_inactive  $color8  $color8  $foreground  $color8   $color8
client.unfocused         $background $background $foreground $background $background
client.urgent            $color1  $color1  $foreground  $color1   $color1
