set $accent #2BB4EA
set $bg #3F3F3F
set $fg #E7F1F0
set $urgent #717857

client.focused          $accent  $bg $fg $accent  $accent
client.unfocused        #A2A9A8 $bg #E7F1F0 #A2A9A8 #A2A9A8
client.focused_inactive #A2A9A8 $bg #E7F1F0 #A2A9A8 #A2A9A8
client.urgent           $urgent  $bg $urgent $urgent $urgent
