set $background #02102D
set $foreground #E9F7F8
set $color0     #010017
set $color1     #91AFB0
set $color2     #9A8FA7
set $color3     #977661
set $color4     #4783AD
set $color5     #817889
set $color6     #3E5991
set $color7     #D8ECED
set $color8     #97A5A6
set $color9     #C1E9EB
set $color10    #CDBEDF
set $color11    #C19477
set $color12    #449EDA
set $color13    #887A95
set $color14    #3F63AF
set $color15    #D8ECED

# target                 border   bg       text     indicator child_border
client.focused           $color4  $color4  $background  $color12  $color4
client.focused_inactive  $color8  $color8  $foreground  $color8   $color8
client.unfocused         $background $background $foreground $background $background
client.urgent            $color1  $color1  $foreground  $color1   $color1
