foreground              #d3c6aa
background              #272e33
cursor                  #a7c080
cursor_text_color       #272e33
selection_foreground    #272e33
selection_background    #a7c080
url_color               #83c092
active_border_color     #a7c080
inactive_border_color   #374145
active_tab_foreground   #272e33
active_tab_background   #a7c080
inactive_tab_foreground #495156
inactive_tab_background #2e383c
tab_bar_background      #272e33
color0  #374145
color1  #e67e80
color2  #a7c080
color3  #dbbc7f
color4  #7fbbb3
color5  #d699b6
color6  #83c092
color7  #d3c6aa
color8  #4f5b58
color9  #e67e80
color10 #a7c080
color11 #dbbc7f
color12 #7fbbb3
color13 #d699b6
color14 #83c092
color15 #d3c6aa
