foreground              #bdbdbd
background              #080808
cursor                  #80a0ff
cursor_text_color       #080808
selection_foreground    #080808
selection_background    #80a0ff
url_color               #79dac8
active_border_color     #80a0ff
inactive_border_color   #2c2c2c
active_tab_foreground   #080808
active_tab_background   #80a0ff
inactive_tab_foreground #4e4e4e
inactive_tab_background #1c1c1c
tab_bar_background      #080808
color0  #323437
color1  #ff5454
color2  #8cc85f
color3  #e3c78a
color4  #80a0ff
color5  #cf87e8
color6  #79dac8
color7  #c6c6c6
color8  #636379
color9  #ff5189
color10 #36c692
color11 #c2c292
color12 #74b2ff
color13 #ae81ff
color14 #85dc85
color15 #e4e4e4
