set -g status-style "fg=#c0caf5"
set -g status-right "#[fg=#7aa2f7,bold] %d %B %y - %H:%M "
set -g window-status-format "#{?#{==:#{session_windows},1},, #[fg=#565f89,nobold]#I.#W }"
set -g window-status-current-format "#{?#{==:#{session_windows},1},, #[fg=#7aa2f7,bold]*.#W }"
set -g pane-border-style "fg=#16161e"
set -g pane-active-border-style "fg=#bb9af7"
