set -g status-style "fg=#cdd6f4"
set -g status-right "#[fg=#89b4fa,bold] %d %B %y - %H:%M "
set -g window-status-format "#{?#{==:#{session_windows},1},, #[fg=#6c7086,nobold]#I.#W }"
set -g window-status-current-format "#{?#{==:#{session_windows},1},, #[fg=#89b4fa,bold]*.#W }"
set -g pane-border-style "fg=#181825"
set -g pane-active-border-style "fg=#f5c2e7"
