set $accent {{color4}}
set $bg {{color0}}
set $fg {{color7}}
set $urgent {{color1}}

client.focused          $accent  $bg $fg $accent  $accent
client.unfocused        {{color8}} $bg {{color7}} {{color8}} {{color8}}
client.focused_inactive {{color8}} $bg {{color7}} {{color8}} {{color8}}
client.urgent           $urgent  $bg $urgent $urgent $urgent
