set -g status-style "fg={{foreground}}"
set -g window-status-format "#{?#{==:#{session_windows},1},, #[fg={{color7}},nobold]#I.#W }"
set -g window-status-current-format "#{?#{==:#{session_windows},1},, #[fg={{color4}},bold]*.#W }"
set -g pane-border-style "fg={{color0}}"
set -g pane-active-border-style "fg={{color5}}"
