backend = "full"

color_space = "lab"
palette = "dark16"
check_contrast = true


[templates]
sway.template = "sway.conf"
sway.target = "~/.config/sway/config.d/theme-colors.conf"

rofi.template = "rofi.rasi"
rofi.target = "~/.config/rofi/colors.rasi"

waybar.template = "waybar.css"
waybar.target = "~/.config/waybar/colors.css"

swaync.template = "swaync.css"
swaync.target = "~/.config/swaync/colors.css"

kitty.template = "kitty.conf"
kitty.target = "~/.config/kitty/theme.conf"

tmux.template = "tmux.conf"
tmux.target = "~/.config/tmux/theme.conf"

nvim.template = "nvim.lua"
nvim.target = "~/.config/nvim/lua/theme/colors.lua"
