include ~/.config/kitty/theme.conf
font_family                 JetBrains Mono
font_size                   12
bold_font                   auto
italic_font                 auto
bold_italic_font            auto
remember_window_size        no
initial_window_width        950
initial_window_height       500
cursor_blink_interval       0.5
cursor_stop_blinking_after  1
scrollback_lines            2000
wheel_scroll_min_lines      1
shell_integration           enabled
background_opacity          0.95
enable_audio_bell           no
hide_window_decorations     yes
dynamic_background_opacity  yes
confirm_os_window_close     0
selection_foreground        none
selection_background        none
cursor_trail                1
shell                       zsh 
window_padding_width        2 0

# Disable tab/window management (using tmux instead)
map ctrl+shift+t            no_op
map ctrl+shift+w            no_op
map ctrl+shift+]            no_op
map ctrl+shift+[            no_op
map ctrl+shift+.            no_op
map ctrl+shift+,            no_op
